codecov:
  notify:
    require_ci_to_pass: no

coverage:
  status:
    patch:
      default:
        target: 95%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: failure
    project:
      default:
        target: 85%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: failure
